[package]
name = "simple-oidc-contour-authserver"
version = "0.1.0"
authors = ["Arthur LE MOIGNE <me@alemoigne.fr>"]
edition = "2018"

[dependencies]
tonic = "0.4"
prost = "0.7"
prost-types = "0.7"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
env_logger = "0.8"
anyhow = "1.0"

[build-dependencies]
tonic-build = "0.4"
