[package]
name = "simple-oidc-contour-authserver"
version = "0.1.0"
authors = ["Arthur LE MOIGNE <me@alemoigne.fr>"]
edition = "2018"

[dependencies]
tonic = "0.4"
prost = "0.7"
prost-types = "0.7"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
env_logger = "0.8"
anyhow = "1.0"
thiserror = "1.0"
async-trait = "0.1.42"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
envy = "0.4"
jsonwebtoken = "7.2"
reqwest = { version  = "0.11", features = ["json"] }

[build-dependencies]
tonic-build = "0.4"

[dev-dependencies]
base64 = "0.13"
