name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Install build depenencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes protobuf-compiler
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
